version: '3.7'

services:
    stop.dev:
        container_name: stop.dev
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                XDEBUG_MODE: ${XDEBUG_MODE}
                XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
                XDEBUG_HANDLER: ${XDEBUG_HANDLER}
        volumes:
            - ./:/app
        depends_on:
            - stop.db

    stop.db:
        container_name: stop.db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: stop
            PGDATA: /docker/dbdata
        volumes:
            - ./docker/dbdata:/var/lib/postgresql/data
            - ./docker/pgsql:/docker-entrypoint-initdb.d
    nginx:
        container_name: nginx
        build: docker/nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./:/app
        depends_on:
            - stop.dev

    mongo:
        container_name: mongo
        image: mongo:latest
        command: mongod --maxConns 10000
        volumes:
            - mongo:/data/db
        ports:
            - "27060:27017"
        networks:
            - bubble
        environment:
            TZ: America/Sao_Paulo
            MONGO_INITDB_DATABASE: stop

volumes:
    mongo:

networks:
    bubble:
        external: true
